[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["ytdl-core"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
